README.md

Simplify the submodule update command by combining it with the `--init` flag. Also addresses the typo in the submodule command.

Simplify submodule update command

---

Dockerfile

I used decktape to export a [Jupyter Notebook Slideshow](https://github.com/damianavila/RISE) last night and found the installation a bit challenging.  In particular, getting the forked version of phantomjs up and running was a bit of a challenge because it dynamically links against several librariesa.
The easiest way I ultimately found to run decktape was to build a [docker](https://github.com/docker/docker) image based on debian:jessie that installed all the dependencies and the pre-built phantomjs.  This PR adds the Dockerfile I used to export my slides.
The expected workflow for using this container would be something like the following:
```
<start local process serving slides on http://localhost:8000/Talk.slides.html >
cd <decktape>
docker build -t decktape .
docker run -it decktape …
```

ENH: Add a Dockerfile.

---

decktape.js

Allow plugins to inform decktape of slide size. Plugins must implement the `size` function. This function is only called if the size is not specified.
I've also moved the setup of page and printer into the configure function to organize the code a bit more.

Allow plugins to inform decktape of slide size if not specified

---

README.md
plugins/bespoke.js

If Bespoke.js is configured in one of the following ways, this converter will be activated.
```js
var bespoke = require('bespoke');
(window.bespoke = bespoke).deck = bespoke.from('.deck', [
// plugins
]);
```
or
```js
var bespoke = require('bespoke'),
extern = require('bespoke-extern');
bespoke.from('.deck', [
// additional plugins
extern(bespoke)
]);
```
More details can be found here: https://github.com/opendevise/bespoke-extern#usage
This plugin auto-advances to the last build item on each slide. Once decktape supports the option to control whether slides are created per fragment, the plugin should be updated accordingly.

Add a native exporter for Bespoke.js

---

README.adoc

Provides updated documentation to reflect changes introduced by PR #58.

Updated download PhantomJS executable instructions for Ubuntu 16.04.

---

plugins/generic.js

Hey, first thanks for writing decktape, quite useful.
Why not solve the screen / print business by allowing users to specify `--cssMedia print` on the command line if desired?  This way the default behavior is preserved (screen), but those with themes that support a print format can also get that behavior.
Thanks!

Allow cssMedia to be specified on command line

---

decktape.js

Dear Antonin,
after starting to [use image elements with data uri resources](https://github.com/posterkit/posterkit-sandbox/commit/fd27782c#diff-170a6d42d4c00a9d6e651244bdb33378R410) in [PosterKit](https://github.com/posterkit/posterkit-sandbox) to work around the [CSS image masking problems with SVG images](https://github.com/posterkit/posterkit-sandbox/issues/2#issuecomment-388431859) (also tracked here as https://github.com/astefanutti/decktape/issues/149), we found DeckTape to stall indefinitely until timing out, obviously not receiving an appropriate page load event.
After reading about [earlier freezing issues of the same origin](https://github.com/GoogleChrome/puppeteer/issues/728#issuecomment-351432657), we found using the `networkidle2` lifecycle event [works great for …

Use "networkidle2" lifecycle event to make page loading work with data uri resources

---

Dockerfile

Make it able to export slides into pdf including Japanese characters such as hiragana, katakana and kanji.

Fonts support for Chinese/Japanese Characters

---

README.adoc

As discussed in issue #165, I'm adding relevant FAQ information about sandbox errors for other Linux users that might run into this issue.

#165: Add FAQ about `no usable sandbox` errors to docs.

---

README.adoc

FAQ entry for --no-sandbox hasn't been updated to use the `--chrome-arg` syntax. This PR fixes this documentation issue.

doc: fixed README FAQ entry about --no-sandbox

---

README.adoc
plugins/nuedeck.js

This plugin is for NueDeck (a reboot of deck.js (and many extensions), using Vue.js, https://github.com/twitwi/nuedeck )
I don't know what is the policy for including new plugins into the main repo:
- NueDeck is currently very new, is this blocking?
- should I update the decktape readme for the PR?
- also, is there a way for a plugin to change the default "pause"?
Thanks for working on decktape.

Add support for NueDeck

---

README.adoc

I've had to hunt around the issue tracker to fix problems with using decktape. I think these are worthwhile to expose in the README and added them to the 'Errors' section - now renamed to 'Troubleshooting'

Add some troubleshooting steps

---

README.adoc

The link poiniting to spectacle's website gave a 404. So updated with the current link

Corrected Spectacle's Link

---

npm-shrinkwrap.json

Hello, and thank you for making decktape!
This PR upgrades npm-shrinkwrap.json to lockfile version 2, which is the format introduced by npm v7. This fixes chrome not being downloaded when installing decktape as a dependency in a project using npm v7+. See https://github.com/puppeteer/puppeteer/issues/6586#issuecomment-958379915. The new format is backward compatible so users of npm v6 and lower should not be impacted.

Upgrade shrinkwrap

---

Dockerfile

Added CHROMIUM_VERSION Dockerfile argument and updated chromium version.
Now it works on Apple M1 arch.
This should fix issue #231

Chromium fix for ARM architectures

---

decktape.js

I added a timeout to `pdf.page` so that you can customize how long you will wait for slides with large assets to finish buffering. 
I had a complicated plotly graph that was causing the buffer to take much longer than the default of 30 seconds. This was the only way I was able to mitigate the issue.

Add timeout to pdf buffering for slide

---

npm-shrinkwrap.json
package.json

Fixes #249
I've tested it with a private presentation and it looked good. Please test it on any test pdfs you might have.
_Note:_ I've not updated `chalk` to the `@latest` version (v5) as chalk migrated to ESM (ECMAScript modules). If you want, I can make a separate PR to migrate decktape to use ESM internally.

fix(deps): update dependencies

---

plugins/reveal.js

This is a workaround for denehyg/reveal.js-menu#99
When the RevealMenu plugin is enabled, there is a menu button on the printed slides.
This change disables that menu during printing.
This isn't necessarily the best possible solution, but since there is no "official" API for updating plugin configuration and the RevealMenu plugin does not expose any destroy or hide button API, this is the best alternative at the moment.

feat(revealjs): disable menu open button

---

.github/workflows/ci.yml

This avoids the CI workflow to run twice on PRs.

Fix CI workflow triggers

---

.github/workflows/ci.yml

It's not the types that prevents the CI workflow from being triggered from the update snapshots one. It's the usage of `secrets.GITHUB_TOKEN` as documented in https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow.

ci: Revert pull_request event types

---

.github/workflows/ci.yml
.github/workflows/update-snapshots.yml

https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/

ci: Trigger CI workflow after the snapshots update

---

.github/workflows/ci.yml

ci: Use workflow_dispatch instead of repository_dispatch

---

README.adoc
plugins/generic.js

Support multiple navigation keys in the generic plugin

---

decktape.js

Do not remove identical image references

---

decktape.js

Decktape doesn't wait for the browser to close before exiting the node process. This causes the browser to crash and not to remove temporary files, leaving them in `/tmp` directory.
See: https://pptr.dev/api/puppeteer.browser.close
Related issue: https://github.com/astefanutti/decktape/issues/295

Fix: asynchronously wait for the browser to close before exiting the process

---

README.adoc

Maybe this works with docker, but with podman, I needed a `:/slides/...`

Fix tiny path issue for docker copy method
